### ISSUE TITLE
Could not found the  GPflow 0.4.0 version

### ISSUE THREAD

**Issue by vinodkkurmi** [thangbui/streaming_sparse_gp#3]
Hi @thangbui , I could not found the  GPflow 0.4.0 version, tried with other versions, it is not working.

I got a segmentation fault error.
Can you please help me regarding this?

Thank you

**Comment by thangbui** [comment]
Hi @vinodkkurmi, 

The 0.4.0 version is here: https://github.com/GPflow/GPflow/tree/0.4.0. Let me know if there are any issues running the code with this version.

This version is pretty dated so it would be good to change our repo to be compatible with GPflow 1.x and 2.x.

**Comment by vinodkkurmi** [comment]
@thangbui Thanks for you quick reply.
I am getting the following error, can you help in that, please  s
1: MatplotlibDeprecationWarning: Support for setting the 'text.latex.preamble' or 'pgf.preamble' rcParam to a list of strings is deprecated since 3.3 and will be removed two minor releases later; set it to a single string instead.

self[key] = other[key]
Illegal instruction (core dumped)

**Comment by thangbui** [comment]
Could you provide a minimal example or point me to the script? 

The matplotlib message is only a warning so it should get through that, but am wondering where `self[key] = other[key]
Illegal instruction (core dumped)` happened.

**Comment by vinodkkurmi** [comment]
Hi @thangbui 
I am using 
1. TensorFlow 1.5 (1.6 and later version giving the problem of  llegal instruction (core dumped))
2. GPflow-0.4.0
 I am getting the following error

Traceback (most recent call last):
  File "run_cla_toy.py", line 71, in <module>
    import osvgpc
  File "//streaming_sparse_gp/code/osvgpc.py", line 8, in <module>
    from gpflow.param import Param, DataHolder
ModuleNotFoundError: No module named 'gpflow.param'

**Comment by thangbui** [comment]
This is strange as I can see  gpflow.param here https://github.com/GPflow/GPflow/blob/0.4.0/gpflow/param.py

Could you check the path and make sure that the right gpflow version is used?

Thanks!
