### ISSUE TITLE
Incorrect equation

### ISSUE THREAD

**Issue by ivetasarfyova** [thangbui/streaming_sparse_gp#5]
Hi :) I was reimplementing your model in another framework, and I think I stumbled upon one discrepancy between what is stated in the paper and the implementation. The difference is in the computation of predictive covariance (appendix B.3.2), where one matrix should be, according to the paper, inversed and transposed while the code indicates that is only inversed. After I removed the matrix's transposition, my model's performance improved. I suppose that the mistake was made while rewriting the equations, and the implementation available within this repository is correct.

The third term of the predictive covariance [https://github.com/thangbui/streaming_sparse_gp/blob/master/code/osgpr.py#L179](https://github.com/thangbui/streaming_sparse_gp/blob/master/code/osgpr.py#L179)

![image](https://user-images.githubusercontent.com/81488189/183048242-0ab1bbfd-9c9a-4936-9842-4986ec630f72.png)

I'm very well aware that my linear algebra skills are limited, so I apologise if I missed some crucial mental step, but I'd love it if you could clarify.

**Comment by thangbui** [comment]
Hi, thanks for the interest in the paper + code!

You are right that the underlined $L_b^{-\intercal}$ should be $L_b^{-1}$. Same for the equation above. Thanks for pointing this out!

Let me know if there are any other issues. I will close this ticket now.
